(defun test-simple ()
  (unless (member :ACT-R *features*)
    (load "/actr/actr7.x/load-single-threaded-act-r.lisp"))
  (load "ptsd.lisp")
  (let ((sim (make-instance 'simulation)))
    (setf (ptev sim) 
          '(20))
    (setf (ptes sim)
          '(0.25))
    (setf (num-days-before sim)
         10)
    (setf (num-days-after sim)
          10)
    (let ((ht (make-hash-table)))
      (setf (gethash :imaginal-activation ht) 4)
      (setf (gethash :bll ht) 0.5)
      (setf (model-params sim) ht))
    
    (setf (logfile sim) "test_simple.csv") 
    (run-simulations sim)))
 
(defun test-gamma-change ()
  "This tests the new 'Special events' feature"
  (unless (member :ACT-R *features*)
    (load "/actr/actr7.x/load-single-threaded-act-r.lisp"))
  (load "ptsd.lisp")
  (let ((sim (make-instance 'simulation)))
    (setf (ptev sim) 
          '(20))
    (setf (ptes sim)
          '(0.25))
    (setf (gamma sim)
          0.9)
    (setf (num-days-before sim)
         10)
    (setf (num-days-after sim)
          10)
    (setf (special-events sim)
          (list (list (* 15 24 60 60)
                      'lower-gamma)
                (list (* 20 24 60 60)
                      #'(lambda (s) (setf (gamma sim)
                                          0.9)))))
    (setf (n sim) 50)
    (let ((ht (make-hash-table)))
      (setf (gethash :imaginal-activation ht) 4)
      (setf (gethash :bll ht) 0.5)
      (setf (model-params sim) ht))
    
    (setf (logfile sim) "test_gamma_change.csv") 
    (run-simulations sim)))
