;;(ql:quickload "split-sequence")
(push :actr-fast *features*)
(load "/actr/actr7.x/load-single-threaded-act-r.lisp")
(load "../../model/ptsd.lisp")
(let ((sim (make-instance 'simulation)))
  (setf (num-slots sim) 8)
  (setf (num-attributes sim) 6)
  (setf (ptes sim) '(0.25))
  (setf (event-frequency sim) 20)
  (setf (gamma sim) 0.95)
  (setf (ptev sim) '(20))
  (setf (n sim) 50)
  (setf (rumination-frequency sim) 0)
  (setf (gethash :rt (model-params sim)) 0.0)
  (setf (gethash :imaginal-activation (model-params sim)) 4.0)
  (setf (gethash :bll (model-params sim)) 0.5)
  ;(setf (special-events sim)
  ;      (list (list (* 110 24 60 60) 'lower-gamma)
  ;	      (list (* 160 24 60 60) #'(lambda (s)
  ;					 (setf (gamma s) 0.90)))))
  (setf (logfile sim) "w=4_gamma=0.95_ptev=20_ptes_0.25_r=0_gamma.csv")
  (run-simulations sim))
(quit)
