(ql:quickload "split-sequence")
(push :actr-fast *features*)
(load "/actr/actr7.x/load-act-r.lisp")
(load "/home/andrea/Documents/Research/PTSD/model/ptsd.lisp")
(let ((sim (make-instance 'simulation)))
  (setf (num-slots sim) 8)
  (setf (num-attributes sim) 6)
  (setf (ptes sim) '(0.25))
  (setf (event-frequency sim) 20)
  (setf (gamma sim) 0.90)
  (setf (ptev sim) '(20))
  (setf (n sim) 50)
  (setf (rumination-frequency sim) 0)
  (setf (gethash :rt (model-params sim)) 0.0)
  (setf (gethash :imaginal-activation (model-params sim)) 4.0)
  (setf (gethash :bll (model-params sim)) 0.5)
  (setf (special-events sim)
        (list (* 110 24 60 60) 'change-gamma))
  (setf (logfile sim) "test_change_gamma.csv")
  (run-simulations sim))
(quit)
