
(load "/actr/actr7.x/load-act-r.lisp")
(load "ptsd.lisp")
(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 0.0)
  (setf (gethash :bll ht) 0.30)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=0.0_bll=0.30.txt") 
(run sim)
(quit)
