(load "/projects/actr/actr7.x/load-act-r.lisp")(load "/home/stocco/Desktop/PTSD/fast/ptsd.lisp")(defparameter sim nil)
(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 10.0)
  (setf (gethash :bll ht) 0.10)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=10.0_bll=0.10.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 10.0)
  (setf (gethash :bll ht) 0.90)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=10.0_bll=0.90.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 10.0)
  (setf (gethash :bll ht) 0.50)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=10.0_bll=0.50.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 10.0)
  (setf (gethash :bll ht) 0.30)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=10.0_bll=0.30.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 10.0)
  (setf (gethash :bll ht) 0.70)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=10.0_bll=0.70.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 5.0)
  (setf (gethash :bll ht) 0.10)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=5.0_bll=0.10.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 5.0)
  (setf (gethash :bll ht) 0.90)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=5.0_bll=0.90.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 5.0)
  (setf (gethash :bll ht) 0.50)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=5.0_bll=0.50.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 5.0)
  (setf (gethash :bll ht) 0.30)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=5.0_bll=0.30.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 5.0)
  (setf (gethash :bll ht) 0.70)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=5.0_bll=0.70.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 2.5)
  (setf (gethash :bll ht) 0.10)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=2.5_bll=0.10.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 2.5)
  (setf (gethash :bll ht) 0.90)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=2.5_bll=0.90.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 2.5)
  (setf (gethash :bll ht) 0.50)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=2.5_bll=0.50.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 2.5)
  (setf (gethash :bll ht) 0.30)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=2.5_bll=0.30.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 2.5)
  (setf (gethash :bll ht) 0.70)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=2.5_bll=0.70.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 7.5)
  (setf (gethash :bll ht) 0.10)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=7.5_bll=0.10.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 7.5)
  (setf (gethash :bll ht) 0.90)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=7.5_bll=0.90.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 7.5)
  (setf (gethash :bll ht) 0.50)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=7.5_bll=0.50.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 7.5)
  (setf (gethash :bll ht) 0.30)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=7.5_bll=0.30.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))

(setf sim (make-instance 'simulation))
(setf (ptev sim) 
      '(1 20 10 5 15))
(setf (ptes sim)
      '(0 1 0.5 0.25 0.75))
(let ((ht (make-hash-table)))
  (setf (gethash :imaginal-activation ht) 7.5)
  (setf (gethash :bll ht) 0.70)
  (setf (model-params sim) ht))

(setf (logfile sim) "simulations_w=7.5_bll=0.70.txt") 
(handler-case
    (run-simulations sim)
  (t (c)
    (format t "Got an exception: ~a~%" c)
    (save-trace sim)))
(quit)