---
title: "GGSeg Experiment"
author: "Andrea Stocco"
date: "6/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggseg)
library(viridis)
```

## R Markdown

Modified version of the test

Random data

```{r}
someData <- tibble(
  region = rep(c("parahippocampal", "medial orbitofrontal", "entorhinal"), 2), 
  p = sample(seq(0,.5,.001), 6),
  groups = c(rep("g1", 3), rep("g2", 3))
)
```

Example visualization:

```{r}
someData %>%
  group_by(groups) %>%
  ggplot() +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = p)) +
  coord_sf(xlim = c(350, 700), ylim=c(240, 450)) +
  facet_wrap(~groups) + scale_fill_viridis(option = "plasma") +theme_minimal()
```

Example visualization:

```{r}
someData %>%
  filter(groups == "g1") %>%
  ggplot() +
  geom_brain(atlas = dk, 
             show.legend = T,
             aes(fill = p)) +
  coord_sf(xlim = c(750, 1050)) +
  scale_fill_viridis(option = "plasma") +
  theme_brain2(text.family = "sans", text.colour="black")
```

Another atlas

```{r}
someData %>%
  filter(groups == "g1") %>%
  ggplot() +
  geom_brain(atlas = ggsegYeo2011::yeo7, 
             show.legend = T,
             aes(fill = p)) +
  coord_sf(xlim = c(750, 1050)) +
  scale_fill_viridis(option = "plasma") +
  theme_brain2(text.family = "sans", text.colour="black")
```

Basic

```{r}
someData = dk_3d %>% 
  filter(surf == "inflated" & hemi == "right") %>% 
  unnest(ggseg_3d) %>% 
  ungroup() %>% 
  select(region) %>% 
  na.omit() %>% 
  mutate(p = sample(seq(0,.5, length.out = 100 ), nrow(.)) %>% 
           round(2)) 

ggseg3d(.data = someData, 
        atlas = dk_3d,
        colour = "p", text = "p") %>% 
  pan_camera("right medial")
```

Test

```{r, fig.width=6, fig.height=5}
data3d <- aseg_3d %>% 
  unnest(cols = ggseg_3d) %>% 
  select(label) %>% 
  filter(grepl("Hippocampus|Amygdala", label)) %>%
  filter(grepl("Left", label)) %>%
  mutate(p = c(1,2)) 

ggseg3d(data3d, 
        atlas = aseg_3d,
        colour = "p", text = "p",
        na.alpha =0,
        palette=c("dodgerblue" = 1, "red" = 2)) %>%
  pan_camera("right medial") %>%
  remove_axes() %>%
  add_glassbrain(hemisphere = "right") %>
```
